INSERT INTO CLASSROOM (id, trainer) VALUES (1, 'John')
INSERT INTO CLASSROOM (id, trainer) VALUES (2, 'Dave')
INSERT INTO CLASSROOM (id, trainer) VALUES (3, 'Matt')
INSERT INTO CLASSROOM (id, trainer) VALUES (4, 'Jordan')
INSERT INTO CLASSROOM (id, trainer) VALUES (5, 'Naomi')
